import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { MongoClient } from 'mongodb';
const RT = new URL('../../.runtime', import.meta.url).pathname;
const PW = readFileSync(join(RT, 'e2e', 'pw-web.txt'), 'utf8').trim();
const U = { email: 'werkbank-e2e@maxenergy.at', name: 'E2E Eins', username: 'e2eeins' };
const mongo = await MongoClient.connect('mongodb://127.0.0.1:27017'); const lcdb = mongo.db('LibreChat');
const lcRequire = createRequire(join(RT, 'librechat', 'api', 'package.json'));
if (!await lcdb.collection('users').findOne({ email: U.email })) { const now = new Date(); await lcdb.collection('users').insertOne({ name: U.name, username: U.username, email: U.email, emailVerified: true, password: lcRequire('bcryptjs').hashSync(PW, 10), avatar: null, provider: 'local', role: 'USER', plugins: [], twoFactorEnabled: false, termsAccepted: true, backupCodes: [], favorites: [], createdAt: now, updatedAt: now, __v: 0 }); }
const b = await chromium.launch(); const p = await (await b.newContext({ locale: 'de-DE', extraHTTPHeaders: { 'x-forwarded-for': '10.97.1.2' } })).newPage();
p.on('request', (r) => { if (r.url().includes('/api/agents/chat')) console.log(r.method(), r.url(), r.postData()); });
p.on('response', async (r) => { if (r.url().includes('/api/agents/chat') && r.request().method() === 'POST') console.log('RESP', await r.text()); });
await p.goto('http://127.0.0.1:3080/login'); await p.fill('input[name=email]', U.email); await p.fill('input[name=password]', PW); await p.click('button[type=submit]');
await p.locator('#prompt-textarea').waitFor();
await p.evaluate(async () => { const t = await (await fetch('/api/auth/refresh', { method: 'POST', credentials: 'include' })).json(); await fetch('/api/keys', { method: 'PUT', headers: { 'content-type': 'application/json', authorization: `Bearer ${t.token}` }, body: JSON.stringify({ name: 'Claude Code', value: JSON.stringify({ apiKey: 'sk-ant-oat01-mock' }), expiresAt: null }) }); });
await p.reload(); await p.locator('#prompt-textarea').fill('Hallo Probe'); await p.getByRole('button', { name: 'Nachricht senden' }).click();
await p.waitForTimeout(4000); console.log('URL', p.url());
await b.close(); await mongo.close();
